### ISSUE TITLE
"!!!" in scripts is not handled

### ISSUE THREAD

**Issue by Adikso** [ReksioEngine/ReksioEngine#23]
Is it some sort of comment or just random symbols put here?

```
EKRAN^HIDE();
GRUPAKAMIENI^SHOW();
GRUPAKAMIENI^PLAY("BEZRUCH");
!!!GRUPAKAMIENI^MONITORCOLLISIONS();
!!!KAMIEN4^MONITORCOLLISION();
!!!KAMIEN5^MONITORCOLLISIONS();
!!!KAMIEN6^MONITORCOLLISIONS();
NAKLADKA^SHOW();
LAWINAANIMO^HIDE();
LAWINAANIMO^SETPRIORITY(0);
EKRANACTIVE^SET(1);
CYFRY^PLAY("PLAY");
WIN^SET(0);
```

**Comment by Dove6** [comment]
You could say an exclamation mark comments out the expression it precedes. However this isn't entirely true as the expression is calculated, only its result is ignored.

One exclamation mark does the job, so I wonder if there is any greater meaning behind putting three bangs there.

(source: trust me dude)

**Comment by Adikso** [comment]
In Piraci:15POSAG there is only one exclamation mark
```
!REKSIO15^SETEVENT("ZPLANSZY12");
!REKSIO15^SETFRAME(10);
!REKSIO15^PLAY("ZPLANSZY12");
COND_JAKI_REKS_POCZ^CHECK(TRUE);
BEH_WROTA_UP^RUNC();
BEH_KAPLONPOCZ^RUNC();
!15POSAG^RUN("S_ODPOWIEDZ","LOAD",ARR_DZWIEKI_OK^GET(2));
!15POSAG^RUN(ARR_DZWIEKI_OK^GET(1),"PLAY");
```

**Comment by Adikso** [comment]
> You could say an exclamation mark comments out the expression it precedes. However this isn't entirely true as the expression is calculated, only its result is ignored.
> 
> One exclamation mark does the job, so I wonder if there is any greater meaning behind putting three bangs there.
> 
> (source: trust me dude)

How do you check that the expression was calculated, but the result was ignored?
I tested with `PRZYGODA^GOTO("MENUGLOWNE");` and it didn't goto, but it doesn't feel like result for me.
