### ISSUE TITLE
Research what CONDITION^CHECK argument is for

### ISSUE THREAD

**Issue by Adikso** [ReksioEngine/ReksioEngine#30]
CONDITION^CHECK accepts some boolean value, but we don't know what is that boolean doing.

https://github.com/ReksioEngine/engine/blob/d6537edcf15144e075dd7ef6557abd84bcf16b3d/src/engine/types/condition.ts#L27

**Comment by Dove6** [comment]
Depending on the value, signals (`ONRUNTIMESUCCESS`, `ONRUNTIMEFAILED`) are run or not.

You can test it e.g. on the `MENUGLOWNE` script on the `WYJSCIEZPROGRAMU` and `CONDKONKURSU` objects:

```diff
 OBJECT=WYJSCIEZPROGRAMU
 WYJSCIEZPROGRAMU:TYPE=BEHAVIOUR
-WYJSCIEZPROGRAMU:CONDITION=CONDKONKURSU
+WYJSCIEZPROGRAMU:CODE={CONDKONKURSU^CHECK(TRUE);}

 OBJECT=CONDKONKURSU
 CONDKONKURSU:TYPE=CONDITION
 CONDKONKURSU:OPERAND1=SYSTEM^GETDATE()
 CONDKONKURSU:OPERATOR=LESS
 CONDKONKURSU:OPERAND2=30401
+CONDKONKURSU:ONRUNTIMESUCCESS={RATUNEK^GOTO("INTRO1");}
+CONDKONKURSU:ONRUNTIMEFAILED={RATUNEK^GOTO("CREDITS");}
```
