### ISSUE TITLE
Invalid CANVAS_OBSERVER^GETGRAPHICSAT arguments

### ISSUE THREAD

**Issue by Adikso** [ReksioEngine/ReksioEngine#45]
In Piraci:24LASER only x, y arguments are passed (and required) to CANVAS_OBSERVER^GETGRAPHICSAT
but our definition looks like that:
```ts
GETGRAPHICSAT(x: number, y: number, onlyVisible: boolean, minZ: number, maxZ: number, includeAlpha?: boolean)
```

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the GETGRAPHICSAT method in the CanvasObserver class to handle cases where only x and y arguments are provided. Added default values for the optional parameters and adjusted the method logic accordingly.

You can review changes in this commit: https://github.com/mnmnk43434/ReksioEngine-ReksioEngine-45/commit/ed2700ee1d0641321d29d4258ab2b2c99cf6b290.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Adikso** [comment]
> Hello, we tried to solve the issue.
> 
> This is what we did:
> 
> Modified the GETGRAPHICSAT method in the CanvasObserver class to handle cases where only x and y arguments are provided. Added default values for the optional parameters and adjusted the method logic accordingly.
> 
> You can review changes in this commit: [mnmnk43434@ed2700e](https://github.com/mnmnk43434/ReksioEngine-ReksioEngine-45/commit/ed2700ee1d0641321d29d4258ab2b2c99cf6b290).
> 
> Caution
> 
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.
> 
> If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

wypierdalaj
